/**
 * Result Card Component
 * 
 * Displays the disease prediction result in a professional medical format.
 * Shows:
 * - Predicted disease name
 * - Confidence score with visual indicator
 * - Color-coded confidence levels
 */

function ResultCard({ prediction }) {
  const { predicted_disease, confidence } = prediction
  const confidencePercent = (confidence * 100).toFixed(2)

  /**
   * Determine confidence level color based on percentage
   * High confidence: green
   * Medium confidence: yellow
   * Low confidence: red
   */
  const getConfidenceColor = () => {
    if (confidence >= 0.7) return 'text-green-600 bg-green-50 border-green-200'
    if (confidence >= 0.4) return 'text-yellow-600 bg-yellow-50 border-yellow-200'
    return 'text-red-600 bg-red-50 border-red-200'
  }

  return (
    <div className="bg-white rounded-lg shadow-lg p-6 animate-fadeIn">
      <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-2">
        <span className="text-3xl">🔬</span>
        Prediction Result
      </h2>

      {/* Disease Name */}
      <div className="mb-6">
        <p className="text-sm font-medium text-gray-600 mb-2">Predicted Disease:</p>
        <p className="text-3xl font-bold text-medical-primary">
          {predicted_disease}
        </p>
      </div>

      {/* Confidence Score */}
      <div>
        <p className="text-sm font-medium text-gray-600 mb-2">Confidence Score:</p>
        <div className={`inline-block px-6 py-3 rounded-lg border-2 ${getConfidenceColor()}`}>
          <p className="text-2xl font-bold">
            {confidencePercent}%
          </p>
        </div>

        {/* Confidence Bar */}
        <div className="mt-4 bg-gray-200 rounded-full h-3 overflow-hidden">
          <div
            className="bg-medical-primary h-full transition-all duration-500 rounded-full"
            style={{ width: `${confidencePercent}%` }}
          />
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-6 p-4 bg-blue-50 border-l-4 border-medical-primary rounded">
        <p className="text-sm text-gray-700">
          <strong>Note:</strong> This prediction is generated by an AI model and should not 
          replace professional medical diagnosis. Please consult a healthcare provider for 
          accurate diagnosis and treatment.
        </p>
      </div>
    </div>
  )
}

export default ResultCard
